import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, EmailStr
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.models import User, Document, Analysis, AuditLog
from app.services.bonus_service import translate_text, generate_voice_summary, send_email_report
from app.services.report_service import generate_pdf_report, generate_docx_report

router = APIRouter(prefix="/api/bonus", tags=["Bonus Features"])


def _get_doc_and_analysis(db: Session, document_id: int, user: User):
    doc = db.query(Document).filter(Document.id == document_id).first()
    if not doc or (doc.owner_id != user.id and user.role != "admin"):
        raise HTTPException(status_code=404, detail="Document not found")
    analysis = db.query(Analysis).filter(Analysis.document_id == doc.id).first()
    if not analysis:
        raise HTTPException(status_code=400, detail="Document not yet analyzed. Run /analyze first.")
    return doc, analysis


# ── 1. Multi-Language Translation ─────────────────────────────────────────────
class TranslateRequest(BaseModel):
    document_id: int
    target_lang: str = "es"
    field: str = "executive_summary"


@router.post("/translate")
def translate_document_field(
    payload: TranslateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    doc, analysis = _get_doc_and_analysis(db, payload.document_id, current_user)
    field_map = {
        "executive_summary":      analysis.executive_summary,
        "payment_terms":          analysis.payment_terms,
        "renewal_clause":         analysis.renewal_clause,
        "confidentiality_clause": analysis.confidentiality_clause,
        "termination_clause":     analysis.termination_clause,
        "responsibilities":       analysis.responsibilities,
    }
    text = field_map.get(payload.field, analysis.executive_summary) or ""
    if not text:
        raise HTTPException(status_code=400, detail=f"Field '{payload.field}' is empty.")
    translated = translate_text(text, target_lang=payload.target_lang)
    return {
        "document": doc.filename,
        "field": payload.field,
        "target_language": payload.target_lang,
        "original": text,
        "translated": translated,
    }


# ── 2. Voice Summary ───────────────────────────────────────────────────────────
@router.get("/voice/{document_id}")
def download_voice(
    document_id: int,
    lang: str = "en",
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    doc, analysis = _get_doc_and_analysis(db, document_id, current_user)
    summary = analysis.executive_summary or "No summary available."
    if lang != "en":
        summary = translate_text(summary, target_lang=lang)
    path = generate_voice_summary(summary, document_id, lang=lang)
    db.add(AuditLog(user_id=current_user.id, action="voice_summary",
                    details=f"{doc.filename} lang={lang}"))
    db.commit()
    return FileResponse(path, media_type="audio/mpeg", filename=path.name)


# ── 3. Email Report Delivery ───────────────────────────────────────────────────
class EmailRequest(BaseModel):
    document_id: int
    recipient_email: EmailStr
    report_format: str = "pdf"
    smtp_host: str
    smtp_port: int = 587
    smtp_user: str
    smtp_password: str
    use_tls: bool = True


@router.post("/email-report")
def email_report(
    payload: EmailRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    doc, analysis = _get_doc_and_analysis(db, payload.document_id, current_user)

    report_path = (
        generate_docx_report(doc, analysis)
        if payload.report_format == "docx"
        else generate_pdf_report(doc, analysis)
    )

    subject = f"AI Contract Risk Report — {doc.filename}"
    body = (
        f"Hello,\n\nPlease find attached the AI Risk Assessment Report for: {doc.filename}\n\n"
        f"Risk Score:       {analysis.risk_score:.0f} / 100\n"
        f"Compliance Score: {analysis.compliance_score or 0:.0f} / 100\n"
        f"Issues Found:     {len(json.loads(analysis.risks_json or '[]'))}\n\n"
        f"Generated by AI Contract & Legal Document Risk Analyzer.\n"
    )

    try:
        send_email_report(
            recipient_email=payload.recipient_email,
            subject=subject,
            body=body,
            attachment_path=report_path,
            smtp_host=payload.smtp_host,
            smtp_port=payload.smtp_port,
            smtp_user=payload.smtp_user,
            smtp_password=payload.smtp_password,
            use_tls=payload.use_tls,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Email delivery failed: {str(e)}")

    db.add(AuditLog(user_id=current_user.id, action="email_report",
                    details=f"{doc.filename} → {payload.recipient_email}"))
    db.commit()
    return {"detail": f"Report sent to {payload.recipient_email} successfully."}


# ── 4. OCR Status ──────────────────────────────────────────────────────────────
@router.get("/ocr-status")
def ocr_status():
    try:
        import pytesseract
        from pdf2image import convert_from_path
        ver = pytesseract.get_tesseract_version()
        return {"ocr_available": True, "tesseract_version": str(ver)}
    except Exception as e:
        return {
            "ocr_available": False,
            "message": str(e),
            "install_hint": (
                "pip install pytesseract pdf2image  "
                "then install Tesseract from https://github.com/UB-Mannheim/tesseract/wiki"
            ),
        }


# ── 5. Compliance Score Breakdown ─────────────────────────────────────────────
@router.get("/compliance/{document_id}")
def compliance_breakdown(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    doc, analysis = _get_doc_and_analysis(db, document_id, current_user)
    risks = json.loads(analysis.risks_json or "[]")

    severity_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for r in risks:
        sev = r.get("severity", "Low")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    clauses_present = sum(1 for f in [
        analysis.payment_terms, analysis.renewal_clause,
        analysis.confidentiality_clause, analysis.termination_clause,
        analysis.responsibilities,
    ] if f)
    clause_pct = round(clauses_present / 5 * 100)
    score = analysis.compliance_score or 0

    return {
        "document": doc.filename,
        "overall_compliance_score": score,
        "risk_score": analysis.risk_score,
        "severity_breakdown": severity_counts,
        "total_issues": len(risks),
        "clause_coverage_percent": clause_pct,
        "clauses_found": clauses_present,
        "clauses_total": 5,
        "grade": (
            "A" if score >= 85 else
            "B" if score >= 70 else
            "C" if score >= 55 else
            "D" if score >= 40 else "F"
        ),
    }